"""Git hook management for Membria."""

import os
from pathlib import Path
import stat
from typing import Optional
from rich.console import Console

console = Console()

HOOK_TEMPLATE = """#!/bin/bash
# Membria Git Hook - Automatically capture session context
# Generated by: membria hooks install

# Only run if we are in a tty (avoid breaking CI)
if [ -t 0 ]; then
    membria engrams capture --auto
fi
"""

class HookManager:
    """Manages installation and removal of Git hooks."""
    
    def __init__(self, project_path: Optional[Path] = None):
        self.project_path = project_path or Path.cwd()
        self.hooks_dir = self.project_path / ".git" / "hooks"
        
    def install(self, hook_name: str = "prepare-commit-msg") -> bool:
        """Installs the Membria hook."""
        if not (self.project_path / ".git").exists():
            console.print("[red]✗ Error: Not a git repository.[/red]")
            return False
            
        self.hooks_dir.mkdir(parents=True, exist_ok=True)
        hook_path = self.hooks_dir / hook_name
        
        # Check if hook already exists
        if hook_path.exists():
            content = hook_path.read_text()
            if "Membria Git Hook" in content:
                console.print(f"[yellow]ℹ {hook_name} already installed.[/yellow]")
                return True
            else:
                # Append or warn? For now, we'll prefix it.
                console.print(f"[yellow]⚠ {hook_name} already exists. Appending Membria logic...[/yellow]")
                with open(hook_path, "a") as f:
                    f.write("\n" + HOOK_TEMPLATE)
        else:
            hook_path.write_text(HOOK_TEMPLATE)
            
        # Make executable
        st = os.stat(hook_path)
        os.chmod(hook_path, st.st_mode | stat.S_IEXEC)
        
        console.print(f"[green]✓ {hook_name} installed successfully.[/green]")
        return True
        
    def uninstall(self, hook_name: str = "prepare-commit-msg") -> bool:
        """Removes the Membria hook."""
        hook_path = self.hooks_dir / hook_name
        if not hook_path.exists():
            return True
            
        content = hook_path.read_text()
        if "Membria Git Hook" in content:
            # If it's ONLY our hook, delete it. If it was appended, we should be careful.
            # Simplified: just unlink for now if it's our template.
            hook_path.unlink()
            console.print(f"[green]✓ {hook_name} removed.[/green]")
        else:
            console.print(f"[yellow]ℹ {hook_name} does not contain Membria logic. Skipping.[/yellow]")
            
        return True
